config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :spaces
  resources :carparks
  root 'home#home'
  get 'contact', to: 'home#contact'
  post 'request_contact', to: 'home#request_contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/space.rb
class Space < ApplicationRecord
  belongs_to :carpark
  has_many :tickets, dependent: :destroy
  validates :carpark, :space_number, :hourly_cost, presence: true
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: [:show, :edit, :update, :destroy]
  before_action :redirect_to_root

  # GET /spaces
  # GET /spaces.json
  def index
    @spaces = Space.all
  end

  # GET /spaces/1
  # GET /spaces/1.json
  def show
  end

  # GET /spaces/new
  def new
    @space = Space.new
  end

  # GET /spaces/1/edit
  def edit
  end

  # POST /spaces
  # POST /spaces.json
  def create
    @space = Space.new(space_params)

    respond_to do |format|
      if @space.save
        format.html { redirect_to @space, notice: 'Space was successfully created.' }
        format.json { render :show, status: :created, location: @space }
      else
        format.html { render :new }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spaces/1
  # PATCH/PUT /spaces/1.json
  def update
    respond_to do |format|
      if @space.update(space_params)
        format.html { redirect_to @space, notice: 'Space was successfully updated.' }
        format.json { render :show, status: :ok, location: @space }
      else
        format.html { render :edit }
        format.json { render json: @space.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spaces/1
  # DELETE /spaces/1.json
  def destroy
    @space.destroy
    respond_to do |format|
      format.html { redirect_to spaces_url, notice: 'Space was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def redirect_to_root
    redirect_to root_path
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_space
    @space = Space.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def space_params
    params.require(:space).permit(:carpark_id, :space_number, :hourly_cost)
  end
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/spaces/_form.html.erb
<%= form_with(model: space, local: true) do |form| %>
  <% if space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(space.errors.count, "error") %> prohibited this space from being saved:</h2>

      <ul>
      <% space.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :carpark_id %>
    <%= form.collection_select :carpark_id, Carpark.order(:name), :id, :name, include_blank: false %>
  </div>

  <div class="field">
    <%= form.label :space_number %>
    <%= form.number_field :space_number %>
  </div>

  <div class="field">
    <%= form.label :hourly_cost %>
    <%= form.text_field :hourly_cost %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/spaces/edit.html.erb
<h1>Editing Space</h1>

<%= render 'form', space: @space %>

<%= link_to 'Show', @space %> |
<%= link_to 'Back', spaces_path %>

app/views/spaces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spaces</h1>

<table>
  <thead>
    <tr>
      <th>Carpark</th>
      <th>Space number</th>
      <th>Hourly cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spaces.each do |space| %>
      <tr>
        <td><%= space.carpark.name %></td>
        <td><%= space.space_number %></td>
        <td><%= space.hourly_cost %></td>
        <td><%= link_to 'Show', space %></td>
        <td><%= link_to 'Edit', edit_space_path(space) %></td>
        <td><%= link_to 'Destroy', space, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Space', new_space_path %>

app/views/spaces/new.html.erb
<h1>New Space</h1>

<%= render 'form', space: @space %>

<%= link_to 'Back', spaces_path %>

app/views/spaces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Carpark:</strong>
  <%= @space.carpark %>
</p>

<p>
  <strong>Space number:</strong>
  <%= @space.space_number %>
</p>

<p>
  <strong>Hourly cost:</strong>
  <%= @space.hourly_cost %>
</p>


<%= link_to 'Edit', edit_space_path(@space) %> |
<%= link_to 'Back', spaces_path %>