config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :spaces
  resources :carparks
  root 'home#home'
  get 'contact', to: 'home#contact'
  post 'request_contact', to: 'home#request_contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def contact
  end

  def request_contact
    name = params[:name]
    email = params[:email]
    phone = params[:phone]
    query = params[:query]
    if email.blank?
      flash[:alert] = I18n.t('home.request_contact.no_email')
    else
      ContactUsMailer.contact_email(email, name, phone, query).deliver_now
      flash[:notice] = I18n.t('home.request_contact.email_sent')
    end
    redirect_to root_path
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.erb
<h1><%= t('.title')%></h1>
<p><%= t('.description')%></p>

<%= form_tag request_contact_path, method: 'post', id: 'contact_form' do %>
  <%= label_tag :name, t('.name'), class: 'form_label_class' %>
  <%= text_field_tag :name, '', title: t('.enter_name'), :required => true, class: 'text_class' %>
  <%= label_tag :email, t('.email'), class: 'form_label_class' %>
  <%= email_field_tag :email, '', title: t('.enter_email'), :required => true, class: 'text_class' %>
  <%= label_tag :phone, t('.phone_number'), class: 'form_label_class' %>
  <%= telephone_field_tag :phone, '', title: t('.enter_phone_number'), :required => true, class: 'text_class' %>
  <%= label_tag :query, t('.query'), class: 'form_label_class' %>
  <%= text_area_tag :query, '', title: t('.enter_query'), size: "100x10", :required => true, class: 'text_class' %>
  <%= submit_tag t('.submit') %>
<% end %>

app/views/home/home.html.erb
<title><%= t('.title')%></title>
<h1><%= t('.title')%></h1>
<p><%= t('.description')%></p>