config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :spaces
  resources :carparks
  root 'home#home'
  get 'contact', to: 'home#contact'
  post 'request_contact', to: 'home#request_contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  before_save :find_space
  before_save :calculate_total_cost

  belongs_to :space, optional: true
  validates :registration_number, :paid_from, :paid_to, presence: true
  validate :validate_dates

  # Method used to take in the carpark provided by the form
  # and return the next available space
  def find_space
    return unless Carpark.find_by_id(space_id)

    @ticket_carpark = Carpark.find_by_id(space_id)
    @spaces = @ticket_carpark.spaces
    @overlap = false
    @spaces.each do |space|
      @space_tickets = Ticket.where(space_id: space.id).all
      @space_tickets.each do |ticket|
        if (Time.parse(ticket.paid_from.strftime('%FT%R'))..Time.parse(ticket.paid_to.strftime('%FT%R')) - 1.minute).overlaps?(Time.parse(paid_from.strftime('%FT%R'))..Time.parse(paid_to.strftime('%FT%R')) - 1.minute)
          @overlap = true
        end
      end
      unless @overlap
        @new_space_id = space.id
        break
      end
      @overlap = false
    end
    puts @new_space_id
    self.space_id = @new_space_id
  end

  # Method used to calculate the cost for the given space
  # provided the time staying
  def calculate_total_cost
    start_time = Time.parse(paid_from.strftime('%FT%R'))
    end_time = Time.parse(paid_to.strftime('%FT%R'))
    @ticket_space = Space.find(space_id)
    self.total_cost = ((end_time - start_time) / 3600.0) * @ticket_space.hourly_cost
  end

  def validate_dates
    return if paid_to.nil? || paid_from.nil?

    # If ending date is before start date
    errors.add(:paid_to, I18n.t('error.ending_before_start')) if paid_to < paid_from
    # If parking time isn't greater than zero
    errors.add(:base, I18n.t('error.time_greater_than_zero')) if (paid_from - paid_to).zero?
    # If starting date is in the past - don't need to check ending time as this would mean
    # it comes before the starting time, raising a different error.
    errors.add(:paid_from, I18n.t('error.starting_time_in_past')) if paid_from.present? && paid_from < Date.today
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: t('.ticket_created') }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: t('.ticket_updated') }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: t('.ticket_destroyed') }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def ticket_params
    params.require(:ticket).permit(:space_id, :registration_number, :paid_from, :paid_to, :total_cost)
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_with(model: ticket, local: true) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label t('.carpark'), class: 'form_label_class' %>
    <%= form.collection_select :space_id, Carpark.order(:name), :id, :name, {}, include_blank: false, class: 'range_class' %>
  </div>

  <div class="field">
    <%= form.label t('.registration_number'), class: 'form_label_class' %>
    <%= form.text_field :registration_number, class: 'text_class' %>
  </div>

  <div class="field">
    <%= form.label t('.paid_from'), class: 'form_label_class' %>
    <%= form.datetime_select :paid_from, { ampm: true, order: [:day, :month, :year], minute_step: 15 }, class: 'date_class' %>
  </div>

  <div class="field">
    <%= form.label t('.paid_to'), class: 'form_label_class' %>
    <%= form.datetime_select :paid_to, { ampm: true, order: [:day, :month, :year], minute_step: 15 }, class: 'date_class' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1><%= t('.editing_ticket')%></h1>

<%= render 'form', ticket: @ticket %>

<%= link_to t('tickets.index.show'), @ticket, class: 'button_class' %>
<%= link_to t('tickets.new.back'), tickets_path, class: 'button_class' %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%=t('.tickets')%></h1>

<table>
  <thead>
    <tr>
      <th><%=t('.space_number')%></th>
      <th><%=t('tickets.form.carpark')%></th>
      <th><%=t('tickets.form.registration_number')%></th>
      <th><%=t('tickets.form.paid_from')%></th>
      <th><%=t('tickets.form.paid_to')%></th>
      <th><%=t('.total_cost')%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.space.space_number %></td>
        <td><%= ticket.space.carpark.name %></td>
        <td><%= ticket.registration_number %></td>
        <td><%= ticket.paid_from.strftime("%d/%m/%Y  %H:%M") %></td>
        <td><%= ticket.paid_to.strftime("%d/%m/%Y  %H:%M") %></td>
        <td><%= number_to_currency(ticket.total_cost, unit: '£') %></td>
        <td><%= link_to t('.show'), ticket %></td>
        <td><%= link_to t('.edit'), edit_ticket_path(ticket) %></td>
        <td><%= link_to t('.destroy'), ticket, method: :delete, data: { confirm: t('.confirmation') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('tickets.new.new_ticket'), new_ticket_path, class: 'button_class' %>

app/views/tickets/new.html.erb
<h1><%= t('.new_ticket')%></h1>

<%= render 'form', ticket: @ticket %>

<%= link_to t('.back'), tickets_path, class: 'button_class' %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%=t('tickets.index.space_number')%>:</strong>
  <%= @ticket.space.space_number %>
</p>

<p>
  <strong><%=t('tickets.form.carpark')%>:</strong>
  <%= @ticket.space.carpark.name %>
</p>

<p>
  <strong><%=t('tickets.form.registration_number')%>:</strong>
  <%= @ticket.registration_number %>
</p>

<p>
  <strong><%=t('tickets.form.paid_from')%>:</strong>
  <%= @ticket.paid_from %>
</p>

<p>
  <strong><%=t('tickets.form.paid_to')%>:</strong>
  <%= @ticket.paid_to %>
</p>

<p>
  <strong><%=t('tickets.index.total_cost')%>:</strong>
  <%= @ticket.total_cost %>
</p>

<%= link_to t('.edit'), edit_ticket_path(@ticket), class: 'button_class' %>
<%= link_to t('tickets.new.back'), tickets_path, class: 'button_class' %>