config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  resources :spaces
  resources :carparks
  root 'home#home'
  get 'contact', to: 'home#contact'
  post 'request_contact', to: 'home#request_contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/carpark.rb
class Carpark < ApplicationRecord
  has_many :spaces, dependent: :destroy
  validates :name, :address, presence: true
  validates :name, uniqueness: true
end

app/controllers/carparks_controller.rb
class CarparksController < ApplicationController
  before_action :set_carpark, only: [:show, :edit, :update, :destroy]
  before_action :redirect_to_root

  # GET /carparks
  # GET /carparks.json
  def index
    @carparks = Carpark.all
  end

  # GET /carparks/1
  # GET /carparks/1.json
  def show
  end

  # GET /carparks/new
  def new
    @carpark = Carpark.new
  end

  # GET /carparks/1/edit
  def edit
  end

  # POST /carparks
  # POST /carparks.json
  def create
    @carpark = Carpark.new(carpark_params)

    respond_to do |format|
      if @carpark.save
        format.html { redirect_to @carpark, notice: 'Carpark was successfully created.' }
        format.json { render :show, status: :created, location: @carpark }
      else
        format.html { render :new }
        format.json { render json: @carpark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carparks/1
  # PATCH/PUT /carparks/1.json
  def update
    respond_to do |format|
      if @carpark.update(carpark_params)
        format.html { redirect_to @carpark, notice: 'Carpark was successfully updated.' }
        format.json { render :show, status: :ok, location: @carpark }
      else
        format.html { render :edit }
        format.json { render json: @carpark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carparks/1
  # DELETE /carparks/1.json
  def destroy
    @carpark.destroy
    respond_to do |format|
      format.html { redirect_to carparks_url, notice: 'Carpark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def redirect_to_root
    redirect_to root_path
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_carpark
    @carpark = Carpark.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def carpark_params
    params.require(:carpark).permit(:name, :address)
  end
end

app/helpers/carparks_helper.rb
module CarparksHelper
end

app/views/carparks/_form.html.erb
<%= form_with(model: carpark, local: true) do |form| %>
  <% if carpark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carpark.errors.count, "error") %> prohibited this carpark from being saved:</h2>

      <ul>
      <% carpark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carparks/edit.html.erb
<h1>Editing Carpark</h1>

<%= render 'form', carpark: @carpark %>

<%= link_to 'Show', @carpark %> |
<%= link_to 'Back', carparks_path %>

app/views/carparks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carparks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carparks.each do |carpark| %>
      <tr>
        <td><%= carpark.name %></td>
        <td><%= carpark.address %></td>
        <td><%= link_to 'Show', carpark %></td>
        <td><%= link_to 'Edit', edit_carpark_path(carpark) %></td>
        <td><%= link_to 'Destroy', carpark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Carpark', new_carpark_path %>

app/views/carparks/new.html.erb
<h1>New Carpark</h1>

<%= render 'form', carpark: @carpark %>

<%= link_to 'Back', carparks_path %>

app/views/carparks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @carpark.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @carpark.address %>
</p>

<%= link_to 'Add Space', new_space_path(carpark_id: @carpark) %>
<%= link_to 'Edit', edit_carpark_path(@carpark) %> |
<%= link_to 'Back', carparks_path %>

<p>Spaces:</p>
<table>
  <% @carpark.spaces.each do |space| %>
    <tr></tr>
    <td>
      <%= space.space_number %>
    </td>
    <td>
      <%= space.hourly_cost %>
    </td>
    <td>
      <%= link_to 'Show', space %>
    </td>
    <td>
      <%= link_to 'Edit', edit_space_path(space) %>
    </td>
    <td>
      <%= link_to 'Destroy', space, :method => :delete, :data => {:confirm => 'Are you sure?'} %>
    </td>
  <% end %>
</table>